# Adresa vašeho nasazeného webu
backend:
  name: git-gateway # Změna z 'github' na 'git-gateway'

# Adresa, kde bude Vercel ověřovat uživatele
site_url: https://muj-blog.netlify.app/ # <-- DOPLŇTE VAŠI VERCEL ADRESU

# Nastavení nahrávání obrázků
media_folder: "src/assets/images/blog" # Kam se mají obrázky ukládat
public_folder: "/src/assets/images/blog" # Jak na ně odkazovat

# Definice kolekcí obsahu
collections:
  - name: "blog" # Identifikátor kolekce
    label: "Příspěvky" # Jméno v administraci
    folder: "src/content/blog" # Složka s Markdown soubory
    create: true # Povolit vytváření nových příspěvků
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formát názvu souboru
    fields: # Políčka pro každý příspěvek
      - { label: "Nadpis", name: "title", widget: "string" }
      - { label: "Datum publikace", name: "pubDate", widget: "datetime" }
      - { label: "Krátký popisek", name: "description", widget: "text" }
      - { label: "Hlavní obrázek", name: "heroImage", widget: "image" }
      - { label: "Obsah článku", name: "body", widget: "markdown" }
