backend:
  name: test-repo # Speciální testovací backend, který neukládá data

media_folder: "public/uploads"

collections:
  - name: "blog"
    label: "Testovací příspěvky"
    folder: "_posts"
    create: true
    fields:
      - { label: "Nadpis", name: "title", widget: "string" }
      - { label: "Obsah", name: "body", widget: "markdown" }
