backend:
  name: git-gateway # Pro Netlify MUSÍ být 'git-gateway'

# Doporučené nastavení pro nahrávání obrázků
media_folder: "public/uploads"
public_folder: "/uploads"

# Definice kolekcí (tato část je v pořádku a může zůstat)
collections:
  - name: "blog"
    label: "Příspěvky"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Nadpis", name: "title", widget: "string" }
      - { label: "Datum publikace", name: "pubDate", widget: "datetime" }
      - { label: "Krátký popisek", name: "description", widget: "text" }
      - { label: "Hlavní obrázek", name: "heroImage", widget: "image" }
      - { label: "Obsah článku", name: "body", widget: "markdown" }
